const { log } = require("console");

function findWord(artical, wordLength, contains) {
	const words = artical.split(" ");
	let possibleWords = [];
	words.forEach((word) => {
		if (word.length === wordLength && word.includes(contains)) {
			possibleWords.push(word);
		}
	});

	return possibleWords;
}

let str = `What Is Crypto Mining?
Crypto mining ensures the security and decentralization of cryptocurrencies such as Bitcoin, which are based on a Proof of Work (PoW) consensus mechanism. It’s the process by which user transactions are verified and added to the blockchain’s public ledger. As such, mining is a critical element that allows Bitcoin to function without the need for a central authority.

Mining operations are also responsible for adding coins to the existing supply. However, crypto mining follows a set of hard-coded rules that govern the mining process and prevent anyone from arbitrarily creating new coins. These rules are built into the underlying cryptocurrency protocols and enforced by the entire network of thousands of nodes.

To create new cryptocurrency units, miners use their computing power to solve complex cryptographic puzzles. The first miner to solve the puzzle has the right to add a new block of transactions to the blockchain and broadcast it to the network.

How Does Crypto Mining Work?
As new blockchain transactions are made, they are sent to a pool called a memory pool. A miner’s job is to verify the validity of these pending transactions and organize them into blocks.

You can think of a block as a page of the blockchain ledger, in which several transactions are recorded (along with other data). More specifically, a mining node is responsible for collecting unconfirmed transactions from the memory pool and assembling them into a candidate block.

The miner then attempts to convert this candidate block into a valid, confirmed block. To do this, the miner must solve a complex mathematical problem that requires a lot of computing resources. However, for each successfully mined block, the miner receives a block reward consisting of newly created cryptocurrencies plus transaction fees. Let’s take a closer look at how it works.

Step 1: Hashing transactions
The first step of mining a block is to take pending transactions from the memory pool and submit them, one by one, through a hash function. Each time a piece of data is run through a hash function, an output of fixed size called a hash is generated.

In the context of mining, the hash of each transaction consists of a string of numbers and letters that acts as an identifier. The transaction hash represents all the information contained in that transaction.

In addition to hashing and listing each transaction individually, the miner also adds a custom transaction, in which they send themselves the block reward. This transaction is called the coinbase transaction and is what creates brand new coins. In most cases, this transaction is the first to be recorded in a new block, followed by all the pending transactions awaiting validation.[07/11, 7:25 am] Only Text: Step 2: Creating a Merkle tree
After each transaction is hashed, the hashes are organized into what is called a Merkle tree (also known as a hash tree). A Merkle tree is generated by organizing transaction hashes into pairs, then hashing them.

The new hash outputs are then organized into pairs and hashed again, and the process is repeated until a single hash is created. This last hash is also called the root hash (or Merkle root) and is basically the hash that represents all the previous hashes used to generate it.
Finding a valid block header (block hash)
A block header acts as an identifier for each individual block, meaning each block has a unique hash. When creating a new block, miners combine the hash of the previous block with the root hash of their candidate block to generate a new block hash. They must also add an arbitrary number known as a nonce.

As such, when trying to validate their candidate block, a miner needs to combine the root hash, the previous block’s hash, and a nonce and put them all through a hash function. Their goal is to do this repeatedly until they can create a valid hash.

The root hash and the hash of the previous block cannot be changed, so miners must change the nonce value several times until a valid hash is found. In order to be considered valid, the output (block hash) must be less than a certain target value determined by the protocol. In Bitcoin mining, the block hash must start with a certain number of zeros — this is called the mining difficulty.

Step 4: Broadcasting the mined block
As we’ve now seen, miners must hash the block header repeatedly using different nonce values. They do so until they find a valid block hash, after which the miner who found it will broadcast this block to the network. All other nodes will check if the block and its hash are valid and, if so, add the new block to their copy of the blockchain.

At this point, the candidate block becomes a confirmed block and all miners move on to mine the next block. Miners who couldn’t find a valid hash on time discard their candidate block and the mining race starts all over again.

What if Two Blocks Are Mined at the Same Time?
Sometimes, two miners broadcast a valid block at the same time and the network ends up with two competing blocks. The miners then start mining the next block based on the block they received first, causing the network to split into two different versions of the blockchain temporarily.

The competition between these blocks continues until the next block is mined on top of one of the competing blocks. When a new block is mined, whichever block came before it is considered the winner. The block that is then abandoned is called an orphan block or a stale block, which causes all the miners who picked that block to switch back to mining the chain of the winning block.

What Is the Mining Difficulty?
The mining difficulty is regularly adjusted by the protocol to ensure a constant rate for new block creation and in turn, steady and predictable issuance of new coins. The difficulty adjusts in proportion to the amount of computational power (hash rate) dedicated to the network.

As such, every time new miners join the network and competition grows, the hashing difficulty increases — preventing the average block time from decreasing. Conversely, if many miners leave the network, the hashing difficulty decreases, making it easier to mine a new block. These adjustments keep the block time constant, regardless of the network’s total hashing power.

Types of Cryptocurrency Mining
There are several ways to mine cryptocurrencies. Equipment and processes change as new hardware and consensus algorithms emerge. Typically, miners use specialized computing units to solve complicated cryptographic equations. We’ll now take a look at some of the most common mining methods.

CPU mining
Central Processing Unit (CPU) mining involves using a computer’s CPU to perform the hash functions required by the PoW model. In Bitcoin’s early days, mining’s costs and barriers to entry were low and its difficulty could be handled by a regular CPU, so anyone could try to mine BTC and other cryptocurrencies.

However, as more people began to mine BTC and the network’s hash rate increased, profitable mining became increasingly difficult. In addition, the advent of specialized mining hardware with greater processing power eventually made CPU mining nearly impossible. Today, CPU mining is likely no longer a viable option, as all miners use specialized hardware.

GPU mining
Graphics Processing Units (GPUs) are designed to process a wide range of applications simultaneously. While they’re typically used for video games or graphics rendering, they can also be used for mining.

GPUs are relatively inexpensive and more flexible than the popular ASIC mining hardware. They can be used to mine some altcoins but their efficiency depends on the mining difficulty and algorithm.

ASIC mining
An Application-Specific Integrated Circuit (ASIC) is designed to serve a single specific purpose. In crypto, the term refers to specialized hardware designed for mining. ASIC mining is known for being highly efficient but expensive at the same time. Because ASIC miners are at the forefront of mining technology, the cost of a unit is much higher than that of a CPU or GPU.

In addition, the constant advancement of ASIC technology can quickly render older ASIC models unprofitable and as such, in need of regular replacement. Even with electricity costs excluded, this makes ASIC mining one of the most expensive ways to mine.

Mining pools
Since the first successful miner is granted a block reward, the probability of finding the correct hash is extremely low. Miners with a small percentage of the mining power have a very small chance of discovering the next block on their own. Mining pools offer a solution to this problem.

Mining pools are groups of miners who pool their resources (hash power) to increase their chances of winning block rewards. When the pool successfully finds a block, the miners in the pool share the reward according to the amount of work they each contributed.

Mining pools can benefit individual miners in terms of hardware and electricity costs, but their domination in mining has raised concerns about a possible 51% attack on networks.

What Is Bitcoin Mining and How Does It Work?
Bitcoin is the most popular and well-established example of a mineable cryptocurrency; Bitcoin mining is based on the PoW consensus algorithm.

PoW is the original blockchain consensus mechanism created by Satoshi Nakamoto and was introduced in the Bitcoin whitepaper in 2008. In a nutshell, PoW determines how a blockchain network reaches consensus across all distributed participants, without third-party intermediaries. It does so by requiring significant computing power to disincentivize bad actors.

As we’ve seen, transactions on a PoW network are verified by miners who compete to solve complex cryptographic puzzles using specialized mining hardware. The first miner to find a valid solution can broadcast their transaction block to the blockchain to receive the block reward.

The amount of crypto in a block reward varies from one blockchain to another. For example, on the Bitcoin blockchain, miners can get 6.25 BTC in block reward as of March 2023. Due to Bitcoin’s halving mechanism, the amount of BTC in a block reward decreases by half every 210,000 blocks (approximately every four years).

Is Crypto Mining Profitable in 2023?
While it is possible to make money mining cryptocurrency, it requires careful consideration, risk management, and research. It also involves investments and risks, such as hardware costs, cryptocurrency price volatility, and cryptocurrency protocol changes. To mitigate these risks, miners often engage in risk management practices and assess the potential costs and benefits of mining before starting.

The profitability of crypto mining depends on several factors. One of them is changes in cryptocurrency prices. When cryptocurrency prices increase, the fiat value of mining rewards also increases. Conversely, profitability can decline along with decreasing prices.

The efficiency of the mining hardware is also a crucial factor in determining the profitability of mining. Mining hardware can be expensive, so miners must balance the cost of the hardware with the potential rewards it can generate. Another factor to consider is the cost of electricity; if it’s too high, it could outweigh earnings and make mining unprofitable.

In addition, mining hardware may need to be upgraded relatively often, as they tend to become obsolete rather quickly. New models will outperform old ones and if miners lack the budget to upgrade their machines, they will likely struggle to remain competitive.

Last but not least, there are the changes that happen at the protocol level. For example, the halving of Bitcoin can affect mining profitability  as it cuts the reward for mining a block in half. In addition, Ethereum switched completely from the PoW to the Proof of Stake (PoS) consensus mechanism in September 2022, which made mining unnecessary.

`;

let words = str.split(" ");

let possibleWords = [];

words.forEach((word) => {
	if (
		word.length === 6 &&
		word.includes("o") &&
		word.includes("e") &&
		!word.includes("r")
	) {
		possibleWords.push(word);
	}
});

console.log(possibleWords);
